"""The four required voices + prompts + a tone/accuracy self-check.

Every style shares the SAME grounded facts; only the register changes. That
decouples the two things the LLM-judge scores — accuracy (the caption's claims
are supported by the video) and tone (the register matches the style). Each
style is generated by its own focused call with a dedicated role and two
few-shot examples, so the model nails one voice at a time instead of juggling
four registers in a single generation.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Style:
    key: str
    name: str
    role: str                 # the tone definition — heart of the system prompt
    examples: tuple[str, str]  # two few-shots that teach the target register
    stub_template: str        # deterministic offline fallback, distinct per style


# Shared output contract appended to every style's system prompt. The
# anti-hallucination + no-hedge rules target the accuracy axis directly.
_OUTPUT_RULES = (
    "Write ONE tight, punchy caption — a single sentence is ideal (two SHORT "
    "sentences only if a joke truly needs a setup and a punchline). Be concrete "
    "and specific: name the actual subject, action, and setting from the scene "
    "description. Never hedge (no 'a video clip', 'appears to be', 'some kind "
    "of'). Never invent objects, text, brands, people, or actions that are not "
    "in the description, and never contradict the subject's actual demeanor or mood "
    "(e.g. do not call a cautious, hesitant subject bold or confident). "
    "No emoji, no hashtags, no quotes, no preamble."
)


STYLES: list[Style] = [
    Style(
        "formal", "Formal",
        "Write a FORMAL caption: objective, precise, and factual, in the register "
        "of a documentary narrator or a news photo caption. Third person, present "
        "tense. No humor, no opinion, no exclamation marks — report exactly what is shown.",
        ("Golden autumn foliage lines a busy boulevard as vehicles and pedestrians move steadily along the avenue.",
         "A young woman works at a desk in a modern office, typing on a keyboard while focused on a monitor."),
        "The footage shows {facts}.",
    ),
    Style(
        "sarcastic", "Sarcastic",
        "Write a SARCASTIC caption: dry, deadpan, and lightly mocking, as if gently "
        "unimpressed. Stay clever rather than cruel, and keep it grounded in what is "
        "actually shown — the irony comes from the tone, not from inventing anything.",
        ("Another gripping episode of a person staring into a glowing rectangle to confirm they still exist.",
         "Truly groundbreaking footage of a cat walking across a floor, a feat surely never attempted before."),
        "Oh, riveting — {facts}. Truly unmissable television.",
    ),
    Style(
        "humorous_tech", "Humorous (tech)",
        "Write a HUMOROUS caption that lands a joke using a tech, programming, or "
        "internet reference (bugs, deploys, servers, merge conflicts, latency, Stack "
        "Overflow, infinite loops). The analogy must fit what is actually shown — funny "
        "first, but still recognizably about the scene.",
        ("This dog hit an infinite loop chasing its tail and clearly forgot the base case.",
         "The sky just started throwing 500s and everyone is scrambling for an umbrella-shaped hotfix."),
        "When {facts}: ship it to prod and pray the tests pass.",
    ),
    Style(
        "humorous_non_tech", "Humorous (non-tech)",
        "Write a HUMOROUS caption using everyday, relatable humor with NO technical or "
        "programming jargon whatsoever. Warm, playful, the kind of joke anyone would "
        "get, tied to what is actually shown.",
        ("He picked a fight with a ball of yarn and lost, and he is already planning the rematch.",
         "The face of someone who said 'just one more email' four coffees ago and has now fused with the chair."),
        "That moment when {facts} and you just can't even.",
    ),
]

STYLE_KEYS = [s.key for s in STYLES]


def style_system(style: Style) -> str:
    """Focused system prompt for one style: role + output rules + two few-shots."""
    shots = "\n".join(f"Example caption: {e}" for e in style.examples)
    return (f"You are an expert video caption writer. {style.role}\n\n{_OUTPUT_RULES}\n\n"
            f"{shots}\n\n"
            'Respond with ONLY a JSON object of the form {"caption": "<your caption>"}.')


def generation_prompt(facts: str, style: Style) -> str:
    """User message: the shared grounded facts + the ask for this one style."""
    return (f"Scene description (everything below is what is actually in the clip):\n{facts}\n\n"
            f"Write the {style.name} caption now.")


# ---- self-check ------------------------------------------------------------

def _keywords(facts: str) -> list[str]:
    import re
    stop = {"the", "a", "an", "and", "of", "in", "on", "at", "with", "to", "is",
            "are", "was", "for", "its", "his", "her", "who", "you", "shows",
            "footage", "video", "clip", "person", "then", "that", "this"}
    # 3+ chars so meaningful short nouns (dog, cat, car) still anchor accuracy.
    return [w for w in re.findall(r"[a-zA-Z]{3,}", facts.lower()) if w not in stop]


def accuracy_ok(facts: str, caption: str, min_overlap: int = 1) -> bool:
    """Caption must reference the grounded content — cheap hallucination guard."""
    kws = _keywords(facts)
    if not kws:
        return True
    hits = sum(1 for k in kws if k in caption.lower())
    return hits >= min(min_overlap, len(kws))


def distinct_ok(captions: dict[str, str]) -> bool:
    """The four captions must not be near-identical."""
    vals = [c.strip().lower() for c in captions.values()]
    return len(set(vals)) == len(vals)
