"""The four required voices + prompts + a tone/accuracy self-check.

Every style shares the SAME grounded facts; only the register changes. That
decouples the two things the LLM-judge scores — accuracy (the caption's claims
are supported by the video) and tone (the register matches the style). Each
style is generated by its own focused call with a dedicated role and two
few-shot examples, so the model nails one voice at a time instead of juggling
four registers in a single generation.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Style:
    key: str
    name: str
    role: str                 # the tone definition — heart of the system prompt
    examples: tuple[str, str]  # two few-shots that teach the target register
    stub_template: str        # deterministic offline fallback, distinct per style


# Shared output contract appended to every style's system prompt. Modeled on the
# official reference captions: CONCISE and WITTY, built around the single most
# striking element — not a dense literal inventory. Style/interpretation is
# rewarded; exhaustive detail is not.
_OUTPUT_RULES = (
    "Write ONE punchy caption, roughly 10-28 words (formal may run to two short "
    "sentences). Zero in on the SINGLE most striking or defining thing in the clip "
    "and build the caption around that — do NOT list many details or write an "
    "inventory. Stay recognizably about the actual scene, but wit, personality, "
    "exaggeration, and figurative comparisons are encouraged. Do not fabricate the "
    "core subject, and do not quote words on signs/logos you cannot clearly read. "
    "No emoji, no hashtags, no quotes, no labels, no preamble. Plain English."
)


STYLES: list[Style] = [
    Style(
        "formal", "Formal",
        "Write a FORMAL caption: a clear, professional description in the register of "
        "a documentary narrator or a news photo caption. Prefer a SINGLE clean sentence "
        "that LEADS with the scene's single most defining element, then adds the main "
        "subject and setting. Specific but not exhaustive — do not list every detail. "
        "Objective and precise; no humor, no opinion.",
        ("A wide urban boulevard lined with golden ginkgo trees in full autumn foliage, with multiple lanes of traffic flowing below high-rise residential buildings.",
         "A young professional woman sits at a desktop computer in a bright, modern open-plan office, focused intently on her screen."),
        "The footage shows {facts}.",
    ),
    Style(
        "sarcastic", "Sarcastic",
        "Write a SARCASTIC caption: dry, deadpan, ironic wit. It can be a conceptual "
        "jab rather than a description — mock-praise the mundane or feign being "
        "thoroughly unimpressed. Clever, not cruel; lightly tied to the scene; "
        "interpretive liberty is welcome. IMPORTANT: vary your STRUCTURE every time — "
        "do NOT open with 'Behold', 'Witness', or 'Ah yes', and do NOT lean on the "
        "'…, proving that…' formula. Mix it up: a flat deadpan statement, a mock-praise, "
        "a rhetorical aside, or a dry interrupted thought all work.",
        ("A city that decided trees were a good idea, which is more than most cities can say.",
         "Just another quiet day in the bustling metropolis of — wait, what city is this again?"),
        "Oh, riveting — {facts}. Truly unmissable television.",
    ),
    Style(
        "humorous_tech", "Humorous (tech)",
        "Write a HUMOROUS caption for a developer/tech audience: a clever programming, "
        "deploy, bug, server, latency, or internet metaphor riffed off the scene. "
        "Meme-style framings ('When your code...') work well. Funny first; the tech "
        "analogy should map onto something actually in the clip.",
        ("Nature's annual deployment: all leaf nodes updated to yellow simultaneously, no breaking changes reported.",
         "When your code runs perfectly in dev but crashes like a wave in production."),
        "When {facts}: ship it to prod and pray the tests pass.",
    ),
    Style(
        "humorous_non_tech", "Humorous (non-tech)",
        "Write a HUMOROUS caption with everyday, relatable humor and NO technical or "
        "programming jargon. Warm, playful; meme-style ('When you...') is welcome. Tie "
        "it to the scene with a wink — interpretive personality is encouraged.",
        ("A tiny cat has gone outside and is now judging everything it sees with great authority.",
         "When you finally leave the house but forget where you were going."),
        "That moment when {facts} and you just can't even.",
    ),
]

STYLE_KEYS = [s.key for s in STYLES]


def style_system(style: Style) -> str:
    """Focused system prompt for one style: role + output rules + two few-shots.
    The examples are drawn from the official reference captions so the model
    matches the exact winning register, length, and wit."""
    shots = "\n".join(f"Example of this style (different clip): {e}" for e in style.examples)
    return (f"You are an expert video caption writer. {style.role}\n\n{_OUTPUT_RULES}\n\n"
            f"{shots}\n\n"
            'Respond with ONLY a JSON object of the form {"caption": "<your caption>"}.')


def generation_prompt(facts: str, style: Style, prior: list[str] | None = None) -> str:
    """User message: the shared grounded facts + the ask for this one style. `prior`
    holds captions already written for OTHER styles of the same clip, so this one is
    told to diverge — maximizing tone separation across the four voices."""
    msg = (f"Scene description (everything below is what is actually in the clip):\n{facts}\n\n"
           f"Write the {style.name} caption now.")
    if prior:
        joined = "\n".join(f"- {c}" for c in prior if c)
        if joined:
            msg += ("\n\nCaptions already written for OTHER styles of this same clip — make "
                    "yours clearly different in wording, sentence structure, and comedic "
                    f"angle (do not echo these):\n{joined}")
    return msg


# Tokens that mark a genuine tech/programming reference — humorous_tech must land one.
TECH_WORDS = {
    "api", "async", "backend", "binary", "boot", "branch", "buffer", "bug", "build",
    "byte", "cache", "ci", "cd", "cloud", "code", "commit", "compile", "compiler",
    "cpu", "crash", "daemon", "data", "database", "debug", "deploy", "deployment",
    "dev", "devops", "docker", "endpoint", "error", "exception", "firewall",
    "framework", "function", "git", "gpu", "hardware", "kernel", "lag", "latency",
    "loop", "memory", "merge", "microservice", "network", "packet", "pipeline",
    "prod", "production", "pull", "push", "query", "queue", "refactor", "render",
    "repo", "rollback", "runtime", "server", "software", "stack", "sync", "syntax",
    "terminal", "test", "thread", "timeout", "update", "upload", "variable", "version",
}


def tech_ok(caption: str) -> bool:
    """True if the caption contains a real tech/programming reference."""
    import re
    return any(w in TECH_WORDS for w in re.findall(r"[a-z]+", caption.lower()))


# ---- self-check ------------------------------------------------------------

def _keywords(facts: str) -> list[str]:
    import re
    stop = {"the", "a", "an", "and", "of", "in", "on", "at", "with", "to", "is",
            "are", "was", "for", "its", "his", "her", "who", "you", "shows",
            "footage", "video", "clip", "person", "then", "that", "this"}
    # 3+ chars so meaningful short nouns (dog, cat, car) still anchor accuracy.
    return [w for w in re.findall(r"[a-zA-Z]{3,}", facts.lower()) if w not in stop]


def accuracy_ok(facts: str, caption: str, min_overlap: int = 1) -> bool:
    """Caption must reference the grounded content — cheap hallucination guard."""
    kws = _keywords(facts)
    if not kws:
        return True
    hits = sum(1 for k in kws if k in caption.lower())
    return hits >= min(min_overlap, len(kws))


def distinct_ok(captions: dict[str, str]) -> bool:
    """The four captions must not be near-identical."""
    vals = [c.strip().lower() for c in captions.values()]
    return len(set(vals)) == len(vals)
